# Numpy

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [4]:
# Cria uma matriz unidimensional
mt = np.array([12,34,26,18,10])
print(mt)
print(type(mt))

[12 34 26 18 10]
<class 'numpy.ndarray'>


In [5]:
#criar o array com um tipo específico
# cria o array como float de 64 bits
mtfloat = np.array([1, 2, 3], dtype = np.float64)
print(mtfloat)
print(type(mtfloat))
mtint = np.array([1, 2, 3], dtype = np.int32)
print(mtint)
print(type(mtint))

[1. 2. 3.]
<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>


In [6]:
# mudar o tipo do array
# Podemos transformar tipos de dados de arrays
mtnew = np.array([1.4, 3.6, -5.1, 9.42, 4.999999])
print(mtnew)
# quando transformamos de float para int os valores são truncados
mtnewint = mtnew.astype(np.int32)
print(mtnewint)

[ 1.4       3.6      -5.1       9.42      4.999999]
[ 1  3 -5  9  4]


In [7]:
# podemos fazer o inverso também.
mt5 = np.array([1, 2, 3, 4])
print(mt5)
mt6 = mt5.astype(float)
print(mt6)

[1 2 3 4]
[1. 2. 3. 4.]


In [8]:
# mais de uma dimensão
# cria um matriz bidimensional
mt7 = np.array([[7,2,23],[12,27,4],[5,34,23]])
print(mt7)

[[ 7  2 23]
 [12 27  4]
 [ 5 34 23]]


In [10]:
# criar arrays vazios tipificados
# empty significa que não são inicializados, não que são vazios
vazio = np.empty([3,2], dtype = int)
print(vazio)
print(f"{'-' * 25}")
# cria uma matriz 4x3 com valores zero
zeros = np.zeros([4,3])
print(zeros)
print(f"{'-' * 25}")
# com valores igual a um
um = np.ones([5,7])
print(um)
print(f"{'-' * 25}")
# cria matriz quadrada com diagonal principal com valores 1 e os outros valores zero
diagonal = np.eye(5)
print(diagonal)


[[         0 1072693248]
 [         0 1073741824]
 [         0 1074266112]]
-------------------------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
-------------------------
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
-------------------------
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [13]:
# valores aleatórios entre zero e um
ale = np.random.random((5))
print(ale)
print(f"{'-' * 70}")
# valores aleatórios distr. normal contendo negativos
ale2= np.random.randn((5))
print(ale2)
print(f"{'-' * 70}")
# valores aleatórios 3 x 4
ale3 = (10*np.random.random((3,4)))
print(ale3)

[0.17958738 0.7896427  0.67016942 0.5985799  0.58743159]
----------------------------------------------------------------------
[-0.09608585 -0.1236159   0.01518447  1.1421354  -0.88464397]
----------------------------------------------------------------------
[[5.03007291 7.34329612 5.1320353  9.30035042]
 [0.1430622  0.32670515 1.52195525 6.34295701]
 [4.91290431 6.48425685 7.1314105  2.20699142]]


In [16]:
# outra forma de gerar aleatórios
# uso de semente
gnr = np.random.default_rng(1)
ale5 = gnr.random(3)
print (ale5)
print(f"{'-' * 50}")
# gerar inteiros
ale6 = gnr.integers(10, size=(3, 4))
print(ale6)

[0.51182162 0.9504637  0.14415961]
--------------------------------------------------
[[8 9 2 3]
 [8 4 2 8]
 [2 4 6 5]]


In [17]:
# unique remove repetições
j = np.array([11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 18, 19, 20])
j = np.unique(j)
print(j)

[11 12 13 14 15 16 17 18 19 20]


In [19]:
# funções específicas
# cria a matriz bidimensional k
k = np.array([[17,22,43],[27,25,14],[15,24,32]])
# Mostra a matriz k
print(k)
print(f"{'-' * 25}")
# Mostra um elemento específico da matriz k
print(k[0][1])
print(f"{'-' * 25}")
# Mostra o tamanho das dimensões da matriz k
print(k.shape)

[[17 22 43]
 [27 25 14]
 [15 24 32]]
-------------------------
22
-------------------------
(3, 3)


In [20]:
# Funções Matemáticas
# Mostra o maior valor da matriz k
print(k.max())
print(f"{'-' * 25}")
# Mostra o menor valor da matriz k
print(k.min())
print(f"{'-' * 25}")
# Mostra a soma dos valores da matriz k
print((k.sum()))
print(f"{'-' * 25}")
# Mostra o valor da média dos valores da matriz k
print(k.mean())
print(f"{'-' * 25}")
# Mostra o valor do desvio padrão (standard deviation) dos valores da matiz k
print(k.std())

43
-------------------------
14
-------------------------
219
-------------------------
24.333333333333332
-------------------------
8.615231988880057


In [22]:
# funções universais, aplicadas a todos os elementos
# Mostra o valor da raiz quadrada de todos elementos
k1 = np.array([1, 4, 9, 16, 25, 36])
print(np.sqrt(k1))
print(f"{'-' * 70}")
# Mostra o valor do exponencial de todos elementos
print(np.exp(k1))

[1. 2. 3. 4. 5. 6.]
----------------------------------------------------------------------
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10 4.31123155e+15]


In [23]:
# Extração de elementos
m = np.array([1, 2, 3, 4, 5, 6])
# Mostra o elemento da posição 2
print(m[1])
print(f"{'-' * 25}")
# Mostra o array criado a partir da posição 0, dois elementos
print(m[0:2])
print(f"{'-' * 25}")
# Mostra o array criado a partir da 2a posição
# até todo o restante do array
print(m[1:])
print(f"{'-' * 25}")
# Mostra o array criado a partir da antepenúltima
#posição até o final
print(m[-3:])

2
-------------------------
[1 2]
-------------------------
[2 3 4 5 6]
-------------------------
[4 5 6]


In [24]:
# Extração de linhas e colunas
l = np.array([[4, 5], [6, 1], [7, 4]])
print(l)
print(f"{'-' * 25}")
#primeira linha, todas as colunas
l_linha_1 = l[0, :]
print(l_linha_1)
print(f"{'-' * 25}")
#segunda linha
l_linha_2 = l[1, :]
print(l_linha_2)
print(f"{'-' * 25}")
#terceira linha
l_linha_3 = l[2, :]
print(l_linha_3)
print(f"{'-' * 25}")
#todas as linhas, primeira coluna
l_coluna_1 = l[:, 0]
print(l_coluna_1)
print(f"{'-' * 25}")
#todas as linhas, segunda coluna
l_coluna_2 = l[:, 1]
print(l_coluna_2)

[[4 5]
 [6 1]
 [7 4]]
-------------------------
[4 5]
-------------------------
[6 1]
-------------------------
[7 4]
-------------------------
[4 6 7]
-------------------------
[5 1 4]


In [25]:
# Adição e multiplicação de matrizes
n = np.array([[1, 2], [3, 4]])
o = np.array([[1, 1], [1, 1]])
res1 = n+o
print(res1)
print(f"{'-' * 25}")
res2 = n*o
print(res2)
print(f"{'-' * 25}")
p = np.array([[1, 2], [3, 4], [5, 6]])
q = np.array([[2, 1]])
print(p+q)

[[2 3]
 [4 5]]
-------------------------
[[1 2]
 [3 4]]
-------------------------
[[3 3]
 [5 5]
 [7 7]]


In [26]:
# transposição, rearranja um conjunto de 15 elementos de 0 a 14 
# em 3 linhas e 5 colunas.
f = np.arange(15).reshape((3, 5))
# mostra a matrizes transposta entre linha e coluna
print(f)
print(f"{'-' * 25}")
s = f.T
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
-------------------------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [27]:
# outra forma de fazer, mesmo resultado
r = np.arange(15).reshape((3, 5))
print(r)
print(f"{'-' * 25}")
# rearranja um conjunto de 15 elementos 
# mostra a matrizes transposta entre linha e coluna
s = r.transpose((1,0))
print(s)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
-------------------------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [30]:
# expressões lógicas
# usando where
# criando matriz com valores aleatórios positivos e negativos
v = np.random.randn(4, 4)
print(v)
print(f"{'-' * 70}")
# criando matriz com valores booleanos baseado no array v
x = (v > 0)
print(x)
print(f"{'-' * 70}")
# criando matriz com valores -1 e 1 baseado nos valores do array x
z = np.where(x > 0, 1, -1)
print(z)

[[ 0.81909192  1.3116746  -1.17045075  0.83662993]
 [ 0.52962321  1.34081828  1.33887987  0.43081798]
 [-0.69639081  0.24195599  0.96326261 -0.27022946]
 [ 0.96817974 -0.32039608 -2.18231372  1.09595256]]
----------------------------------------------------------------------
[[ True  True False  True]
 [ True  True  True  True]
 [False  True  True False]
 [ True False False  True]]
----------------------------------------------------------------------
[[ 1  1 -1  1]
 [ 1  1  1  1]
 [-1  1  1 -1]
 [ 1 -1 -1  1]]
