# Formação Cientista de Dados - Fernando Amaral e Jones Granatyr
# Redes neurais artificiais com keras

In [3]:
pip install keras

Note: you may need to restart the kernel to use updated packages.


In [13]:
pip install tensorflow

                                              0.0/276.6 MB ? eta -:--:--
                                              0.2/276.6 MB 3.3 MB/s eta 0:01:25
                                              0.4/276.6 MB 4.0 MB/s eta 0:01:09
                                              0.6/276.6 MB 4.9 MB/s eta 0:00:57
                                              0.9/276.6 MB 4.8 MB/s eta 0:00:57
                                              1.3/276.6 MB 5.3 MB/s eta 0:00:52
                                              1.3/276.6 MB 4.7 MB/s eta 0:00:59
                                              1.7/276.6 MB 5.1 MB/s eta 0:00:55
                                              2.0/276.6 MB 5.4 MB/s eta 0:00:52
                                              2.2/276.6 MB 5.5 MB/s eta 0:00:51
                                              2.5/276.6 MB 5.3 MB/s eta 0:00:52
                                              2.9/276.6 MB 5.4 MB/s eta 0:00:51
                                              3

In [22]:
pip freeze > requirements.txt

Note: you may need to restart the kernel to use updated packages.


In [18]:
# Importação das bibliotecas
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras import utils

In [19]:
# Carregamento da base de dados e criação dos previsores (variáveis independentes - X) e da classe (variável dependente - y)
base = datasets.load_iris()
previsores = base.data
classe = base.target
classe

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [20]:
# Transformação da classe para o formato "dummy", pois temos uma rede neural com 3 neurônios na camada de saída
classe_dummy = utils.to_categorical(classe)
classe_dummy

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [21]:
# Divisão da base de dados entre treinamento e teste (30% para testar e 70% para treinar)
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(previsores,
                                                                  classe_dummy,
                                                                  test_size = 0.3,
                                                                  random_state = 0)

In [23]:
# Criação da estrutura da rede neural com a classe Sequential (sequência de camadas)
modelo = Sequential()
# Primeira camada oculta, 5 neuronios, 4 neuronios de entrada
modelo.add(Dense(units = 5, input_dim = 4))
# Segunda camada oculta
modelo.add(Dense(units = 4))
# Terceira camada oculta
# Função softmax porque temos um problema de classificação com mais de duas classes 
# (é gerada uma probabilidade em cada neurônio)
modelo.add(Dense(units = 3, activation = 'softmax'))

In [24]:
# Visualização da estrutura da rede neural
modelo.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 5)                 25        
                                                                 
 dense_1 (Dense)             (None, 4)                 24        
                                                                 
 dense_2 (Dense)             (None, 3)                 15        
                                                                 
Total params: 64 (256.00 Byte)
Trainable params: 64 (256.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [25]:
# Configuração dos parâmetros da rede neural (adam = algoritmo para atualizar os pesos e loss = cálculo do erro)
modelo.compile(optimizer = 'adam', loss = 'categorical_crossentropy',
               metrics = ['accuracy'])
# Treinamento, dividindo a base de treinamento em uma porção para validação (validation_data)
modelo.fit(X_treinamento, y_treinamento, epochs = 1000,
           validation_data = (X_teste, y_teste))

Epoch 1/1000
4/4 [==============================] - 3s 176ms/step - loss: 4.5366 - accuracy: 0.3714 - val_loss: 5.5777 - val_accuracy: 0.2444
Epoch 2/1000
4/4 [==============================] - 0s 83ms/step - loss: 4.2631 - accuracy: 0.3714 - val_loss: 5.2713 - val_accuracy: 0.2444
Epoch 3/1000
4/4 [==============================] - 0s 47ms/step - loss: 4.0273 - accuracy: 0.3714 - val_loss: 4.9895 - val_accuracy: 0.2444
Epoch 4/1000
4/4 [==============================] - 0s 38ms/step - loss: 3.8159 - accuracy: 0.3714 - val_loss: 4.7442 - val_accuracy: 0.2444
Epoch 5/1000
4/4 [==============================] - 0s 33ms/step - loss: 3.6467 - accuracy: 0.3714 - val_loss: 4.5341 - val_accuracy: 0.2444
Epoch 6/1000
4/4 [==============================] - 0s 40ms/step - loss: 3.5024 - accuracy: 0.3714 - val_loss: 4.3564 - val_accuracy: 0.2444
Epoch 7/1000
4/4 [==============================] - 0s 35ms/step - loss: 3.3732 - accuracy: 0.3714 - val_loss: 4.2031 - val_accuracy: 0.2444
Epoch 8/1000

In [26]:
# Previsões e mudar a variável para True ou False de acordo com o threshold 0.5
previsoes = modelo.predict(X_teste)
previsoes = (previsoes > 0.5)
previsoes

2/2 [==============================] - 0s 4ms/step


array([[False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [False, False,  True],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [ True, False, False],
       [False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [Fa

In [27]:
# Como é um problema com três saídas, precisamos buscar a posição que possui o maior valor (são retornados 3 valores)
y_teste_matrix = [np.argmax(t) for t in y_teste]
y_previsao_matrix = [np.argmax(t) for t in previsoes]

In [28]:
# Geração da matriz de confusão
confusao = confusion_matrix(y_teste_matrix, y_previsao_matrix)
confusao

array([[16,  0,  0],
       [ 0, 17,  1],
       [ 0,  0, 11]], dtype=int64)